#!/usr/bin/env python3
"""Generate the paper's evidence tables (.tex) from authoritative JSON artifacts.

WHY (zero hand transcription -- viva defence of reproducibility):
    Numbers in a paper drift the moment a human copies them from a console into a
    table. Here the ONLY authoritative source of a result is data/analysis/metrics.json
    (written by run_simulation.py from the logged decision records). This script DERIVES
    the LaTeX tables from that JSON. Re-run the analysis and the tables regenerate; no
    number is ever typed by hand. Every emitted .tex file carries an AUTO-GENERATED
    banner so no one edits the derived artifact instead of the source.

    metrics.json (owner) --> paper/tables/*.tex (derived) --> main.tex \\input --> PDF

USAGE
    python scripts/run_simulation.py          # writes data/analysis/metrics.json
    python scripts/make_paper_tables.py       # writes paper/tables/*.tex
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(__file__)
METRICS_JSON = os.path.join(HERE, "..", "data", "analysis", "metrics.json")
MODEL_JSON = os.path.join(HERE, "..", "data", "models", "pilot_hmm.json")
TABLES_DIR = os.path.join(HERE, "..", "paper", "tables")

BANNER = (
    "% AUTO-GENERATED by scripts/make_paper_tables.py.\n"
    "% DO NOT EDIT BY HAND -- edit the analysis and regenerate (make paper).\n"
)

# (label, json key, formatter). None values render as an em-dash.
_ROWS = [
    ("Interruption burden (s) $\\downarrow$", "interruption_burden_s", "{:.2f}"),
    ("Min.\\ separation (m) $\\uparrow$", "min_separation", "{:.2f}"),
    ("Hazard sensitivity $\\uparrow$", "hazard_sensitivity", "{:.2f}"),
    ("Hazard specificity $\\uparrow$", "hazard_specificity", "{:.2f}"),
    ("False-stop rate $\\downarrow$", "false_stop_rate", "{:.2f}"),
    ("Anticipation lead time (s) $\\uparrow$", "anticipation_lead_time_s", "{:.3f}"),
    ("Stop episodes", "stop_episodes", "{:d}"),
    ("Slowdown episodes", "slowdown_episodes", "{:d}"),
    ("Unnecessary interruption (s)", "unnecessary_interruption_s", "{:.2f}"),
    ("Hazard response latency (s) $\\downarrow$", "hazard_response_latency_s", "{:.3f}"),
]


def _cell(value, fmt: str) -> str:
    if value is None:
        return "--"
    try:
        return fmt.format(value)
    except (ValueError, TypeError):
        return str(value)


def _escape(text: str) -> str:
    return text.replace("_", "\\_")


def _table(metrics: dict, columns, col_titles, caption: str, label: str) -> str:
    ncol = len(columns)
    colspec = "l" + "r" * ncol
    lines = [BANNER]
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append(f"\\begin{{tabular}}{{{colspec}}}")
    lines.append("\\toprule")
    header = "Metric & " + " & ".join(col_titles) + " \\\\"
    lines.append(header)
    lines.append("\\midrule")
    for row_label, key, fmt in _ROWS:
        cells = [_cell(metrics[c].get(key), fmt) for c in columns]
        lines.append(f"{row_label} & " + " & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def _model_validation_table(model: dict) -> str:
    """Render participant-held-out development validation from the active model.

    Unlike the controller-comparison tables, this table is based on labelled real
    development recordings. Its caption and row labels keep the online/offline
    distinction visible and prevent this diagnostic from being mistaken for a
    participant safety outcome.
    """
    validation = model["validation"]
    recalls = validation["per_phase_recall"]
    summary = model["data_summary"]
    participants = summary["participants"]
    folds = validation.get("folds", [])

    lines = [BANNER]
    lines.extend(
        [
            "\\begin{table}[t]",
            "\\centering",
            "\\caption{Leave-one-participant-out phase-recognition development "
            "validation from the active model artifact. Offline Viterbi decoding "
            "uses the complete trial; the causal forward filter is the estimate "
            "closest to live operation. These are model-development diagnostics, "
            "not safety outcomes or final participant-study results.}",
            "\\label{tab:model-validation}",
            "\\begin{tabular}{lr}",
            "\\toprule",
            "Measure & Value \\\\",
            "\\midrule",
            f"Development participants & {len(participants)} \\\\",
            f"Accepted trials & {summary['complete_trials']} \\\\",
            f"Labelled frames & {sum(summary['label_counts'].values())} \\\\",
            f"Offline Viterbi accuracy & {validation['accuracy']:.3f} \\\\",
            f"Offline balanced accuracy & {validation['balanced_accuracy']:.3f} \\\\",
            f"Causal-filter accuracy & {validation['online_filter_accuracy']:.3f} \\\\",
            f"Causal-filter balanced accuracy & {validation['online_filter_balanced_accuracy']:.3f} \\\\",
            f"Approaching recall & {recalls['approaching']:.3f} \\\\",
            f"Working recall & {recalls['working']:.3f} \\\\",
            f"Retreating recall & {recalls['retreating']:.3f} \\\\",
        ]
    )
    if folds:
        fold_text = ", ".join(
            f"{_escape(str(f['participant_id']))}: {f['accuracy']:.3f}" for f in folds
        )
        lines.append(f"Fold accuracy & \\multicolumn{{1}}{{l}}{{{fold_text}}} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}"])
    return "\n".join(lines) + "\n"


def main() -> None:
    if not os.path.exists(METRICS_JSON):
        sys.stderr.write(
            f"error: {os.path.normpath(METRICS_JSON)} not found.\n"
            "Run `python scripts/run_simulation.py` first to produce it.\n"
        )
        sys.exit(1)

    if not os.path.exists(MODEL_JSON):
        sys.stderr.write(f"error: {os.path.normpath(MODEL_JSON)} not found.\n")
        sys.exit(1)

    with open(METRICS_JSON, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    with open(MODEL_JSON, "r", encoding="utf-8") as fh:
        model = json.load(fh)
    metrics = data["metrics"]

    os.makedirs(TABLES_DIR, exist_ok=True)

    three_rung = _table(
        metrics,
        columns=["fixed_zone", "dynamic_ssm", "adaptive"],
        col_titles=["Fixed-zone", "Dynamic SSM", "Adaptive"],
        caption=(
            "Three-rung comparison on the identical held-out trace. "
            "Fixed-zone is deployed practice; Dynamic SSM is the speed-aware "
            "ISO/TS~15066 envelope alone; Adaptive adds the learned state layer "
            "and horizon prediction on top of the envelope floor. "
            "(Synthetic pipeline-validation numbers; replaced by pilot data.)"
        ),
        label="tab:three_rung",
    )
    ablation = _table(
        metrics,
        columns=["adaptive", "adaptive_no_pred", "adaptive_no_state"],
        col_titles=["Full", "$-$Prediction", "$-$State"],
        caption=(
            "Ablation: the full system with one ingredient removed at a time, "
            "same trace. Removing the state layer collapses the interruption "
            "burden toward the bare envelope; prediction is a redundant "
            "anticipation net here. (Synthetic; replaced by pilot data.)"
        ),
        label="tab:ablation",
    )

    model_validation = _model_validation_table(model)

    for name, content in (
        ("three_rung.tex", three_rung),
        ("ablation.tex", ablation),
        ("model_validation.tex", model_validation),
    ):
        path = os.path.join(TABLES_DIR, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {os.path.normpath(path)}")


if __name__ == "__main__":
    main()
